"""phase2 fx forecast data_mode insight_kind

Revision ID: 6bc07a2e224c
Revises: 798f7e215a4c
Create Date: 2026-08-27 02:39:38.914337

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bc07a2e224c'
down_revision: Union[str, None] = '798f7e215a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic's autogenerate diffs column *types*, not the value lists of
    # existing Postgres native enums, so new values added to EventType,
    # EventEntityType, and AIRunPurpose (packages/db/enums.py) are never
    # picked up automatically — add them explicitly. Safe to run inside this
    # migration's transaction on Postgres 12+ (server is 16.x here) since
    # nothing in this same migration inserts rows using these new values.
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'FX_MOVE'")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'MARGIN_THRESHOLD_CROSSED'")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'FX_DRIVEN_OPPORTUNITY'")
    op.execute("ALTER TYPE evententitytype ADD VALUE IF NOT EXISTS 'FX_PAIR'")
    op.execute("ALTER TYPE airunpurpose ADD VALUE IF NOT EXISTS 'THESIS'")
    op.execute("ALTER TYPE airunpurpose ADD VALUE IF NOT EXISTS 'COUNTERTHESIS'")
    op.execute("ALTER TYPE airunpurpose ADD VALUE IF NOT EXISTS 'MISSING_DATA_ANALYSIS'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('forecast_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_horizon_days', sa.Integer(), nullable=False),
    sa.Column('predicted_direction', sa.Enum('BULLISH', 'NEUTRAL', 'BEARISH', name='forecastdirection'), nullable=False),
    sa.Column('predicted_probability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('confidence_tier', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidencetier'), nullable=False),
    sa.Column('is_calibrated', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_outcome', sa.String(length=32), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_run.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_product_id'), 'forecast', ['product_id'], unique=False)
    op.create_table('fx_observation',
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('provider_name', sa.String(length=32), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parser_name', sa.String(), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('extraction_method', postgresql.ENUM('HTML_SELECTOR', 'JSON_FIELD', 'API_RESPONSE', 'MANUAL', 'FIXTURE', 'DERIVED', name='extractionmethod', create_type=False), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'quote_currency', 'source_id', 'observed_at')
    )
    op.create_index(op.f('ix_fx_observation_base_currency'), 'fx_observation', ['base_currency'], unique=False)
    op.create_index(op.f('ix_fx_observation_quote_currency'), 'fx_observation', ['quote_currency'], unique=False)

    # insight.kind: add nullable, backfill from the known title strings this
    # codebase has ever written (docs/ADR/0008-insight-kind-enum.md), then
    # tighten to NOT NULL. Any row whose title doesn't match a known mapping
    # falls back to RECOMMENDATION rather than guessing a more specific kind.
    insight_kind_enum = sa.Enum(
        'WHY_NOW', 'COUNTER_ARGUMENT', 'THESIS', 'COUNTERTHESIS', 'MISSING_DATA', 'RECOMMENDATION',
        name='insightkind',
    )
    insight_kind_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('insight', sa.Column('kind', insight_kind_enum, nullable=True))
    op.execute("UPDATE insight SET kind = 'WHY_NOW'::insightkind WHERE title = 'Why Now'")
    op.execute("UPDATE insight SET kind = 'COUNTER_ARGUMENT'::insightkind WHERE title = 'Counter-Argument'")
    op.execute("UPDATE insight SET kind = 'RECOMMENDATION'::insightkind WHERE kind IS NULL")
    op.alter_column('insight', 'kind', nullable=False)
    op.create_index(op.f('ix_insight_kind'), 'insight', ['kind'], unique=False)

    # source.data_mode: add nullable, backfill from the existing is_mock
    # boolean (docs/ADR/0007-explicit-data-mode-field.md), then tighten to
    # NOT NULL. No existing source can be MANUAL, so is_mock fully determines
    # this backfill with no ambiguity.
    data_mode_enum = sa.Enum('MOCK', 'LIVE', 'MANUAL', name='datamode')
    data_mode_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('source', sa.Column('data_mode', data_mode_enum, nullable=True))
    op.execute(
        "UPDATE source SET data_mode = (CASE WHEN is_mock THEN 'MOCK' ELSE 'LIVE' END)::datamode"
    )
    op.alter_column('source', 'data_mode', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Note: the eventtype/evententitytype/airunpurpose enum values added in
    # upgrade() are intentionally NOT removed here. Postgres has no DROP
    # VALUE for native enums; removing one requires rebuilding the type
    # (rename, recreate without the value, repoint every column, drop the
    # old type) and re-validating that no existing row still uses it — sized
    # risk that isn't worth taking for a downgrade path. Leftover unused
    # enum values are harmless.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'data_mode')
    op.drop_index(op.f('ix_insight_kind'), table_name='insight')
    op.drop_column('insight', 'kind')
    op.drop_index(op.f('ix_fx_observation_quote_currency'), table_name='fx_observation')
    op.drop_index(op.f('ix_fx_observation_base_currency'), table_name='fx_observation')
    op.drop_table('fx_observation')
    op.drop_index(op.f('ix_forecast_product_id'), table_name='forecast')
    op.drop_table('forecast')
    # ### end Alembic commands ###

    # op.drop_column()/op.drop_table() above drop the columns/tables but not
    # the enum types those columns used — Postgres enum types are independent
    # objects. Drop them explicitly so upgrade() can recreate them cleanly
    # (verified via a manual downgrade -> upgrade round-trip during Phase 2
    # development; without this, re-running upgrade() fails with
    # "type already exists").
    sa.Enum(name='datamode').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='insightkind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='forecastdirection').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='confidencetier').drop(op.get_bind(), checkfirst=True)
