"""initial schema

Revision ID: 798f7e215a4c
Revises:
Create Date: 2026-08-26 04:51:47.454683

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "798f7e215a4c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before any table uses the vector column type below.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_run",
        sa.Column(
            "run_type",
            sa.Enum("INGEST", "MATCH", "SCORE", "FULL", name="analysisruntype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "SUCCEEDED", "FAILED", "PARTIAL", name="analysisrunstatus"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("triggered_by", sa.String(length=64), nullable=False),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "brand",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("name_normalized", sa.String(length=255), nullable=False),
        sa.Column("aliases", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_brand_name_normalized"), "brand", ["name_normalized"], unique=False)
    op.create_table(
        "manufacturer",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("name_normalized", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manufacturer_name_normalized"), "manufacturer", ["name_normalized"], unique=False
    )
    op.create_table(
        "market",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "raw_object",
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_table(
        "source",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "MARKETPLACE_HTML",
                "MARKETPLACE_API",
                "GOVERNMENT_API",
                "COMMUNITY_FORUM",
                "NEWS",
                "SOCIAL",
                "FIXTURE",
                "MANUAL",
                name="sourcetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "trust_tier",
            sa.Enum(
                "OFFICIAL",
                "PRIMARY",
                "REPUTABLE_SECONDARY",
                "MARKETPLACE",
                "COMMUNITY",
                "SOCIAL",
                "UNKNOWN",
                name="trusttier",
            ),
            nullable=False,
        ),
        sa.Column(
            "factual_reliability",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="reliabilitylevel"),
            nullable=False,
        ),
        sa.Column(
            "signal_value",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="reliabilitylevel"),
            nullable=False,
        ),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "watchlist_item",
        sa.Column("user_email", sa.String(length=255), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum("PRODUCT", "BRAND", "CATEGORY", "KEYWORD", name="watchlistentitytype"),
            nullable=False,
        ),
        sa.Column("entity_ref", sa.String(length=255), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_run",
        sa.Column("analysis_run_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "ENTITY_MATCH_JUDGE",
                "NAME_NORMALIZATION",
                "CATEGORY_CLASSIFICATION",
                "OPPORTUNITY_NARRATIVE",
                "COUNTER_ARGUMENT",
                "EMBEDDING",
                name="airunpurpose",
            ),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cached_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "status", sa.Enum("SUCCESS", "FAILED", "DISABLED", name="airunstatus"), nullable=False
        ),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event",
        sa.Column(
            "entity_type",
            sa.Enum("PRODUCT", "PRODUCT_VARIANT", "OFFER", "SELLER", name="evententitytype"),
            nullable=False,
        ),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "PRICE_DROP",
                "PRICE_RISE",
                "NEW_SELLER",
                "SELLER_EXIT",
                "STOCK_OUT",
                "RESTOCK",
                "NEW_PRODUCT",
                "REVIEW_ACCELERATION",
                "OPPORTUNITY_SCORE_CHANGE",
                name="eventtype",
            ),
            nullable=False,
        ),
        sa.Column("previous_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_pct", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("analysis_run_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_entity_id"), "event", ["entity_id"], unique=False)
    op.create_table(
        "marketplace",
        sa.Column("market_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "marketplace_type",
            sa.Enum(
                "ECOMMERCE_GENERAL",
                "ECOMMERCE_MARKETPLACE",
                "C2C",
                "BRAND_DIRECT",
                name="marketplacetype",
            ),
            nullable=False,
        ),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["market.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product",
        sa.Column("canonical_title", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("brand_id", sa.UUID(), nullable=True),
        sa.Column("manufacturer_id", sa.UUID(), nullable=True),
        sa.Column(
            "primary_identifier_type",
            sa.Enum(
                "JAN",
                "EAN",
                "UPC",
                "GTIN",
                "ISBN",
                "MPN",
                "MODEL_NUMBER",
                "NONE",
                name="identifiertype",
            ),
            nullable=False,
        ),
        sa.Column("primary_identifier", sa.String(length=64), nullable=True),
        sa.Column(
            "status", sa.Enum("ACTIVE", "MERGED", "SPLIT", name="productstatus"), nullable=False
        ),
        sa.Column("merged_into_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brand.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manufacturer_id"],
            ["manufacturer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_snapshot",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_object_id", sa.UUID(), nullable=True),
        sa.Column("parser_name", sa.String(), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "HTML_SELECTOR",
                "JSON_FIELD",
                "API_RESPONSE",
                "MANUAL",
                "FIXTURE",
                "DERIVED",
                name="extractionmethod",
            ),
            nullable=False,
        ),
        sa.Column(
            "status", sa.Enum("SUCCESS", "FAILED", "PARTIAL", name="snapshotstatus"), nullable=False
        ),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_object_id"],
            ["raw_object.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "source_url", "retrieved_at"),
    )
    op.create_table(
        "insight",
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("narrative", sa.Text(), nullable=False),
        sa.Column("supporting_facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_ai_generated", sa.Boolean(), nullable=False),
        sa.Column("ai_assisted_fields", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("analysis_run_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("source_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parser_name", sa.String(), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "HTML_SELECTOR",
                "JSON_FIELD",
                "API_RESPONSE",
                "MANUAL",
                "FIXTURE",
                "DERIVED",
                name="extractionmethod",
            ),
            nullable=False,
        ),
        sa.Column("model_provider", sa.String(), nullable=True),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("ai_run_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ai_run_id"],
            ["ai_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_insight_product_id"), "insight", ["product_id"], unique=False)
    op.create_table(
        "opportunity",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column(
            "opportunity_type", sa.Enum("IMPORT_RESALE", name="opportunitytype"), nullable=False
        ),
        sa.Column("opportunity_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("sub_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("weights_version", sa.String(length=32), nullable=False),
        sa.Column("economics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "regulation_status",
            sa.Enum(
                "UNKNOWN",
                "LIKELY_LOW",
                "REVIEW_REQUIRED",
                "KNOWN_RESTRICTED",
                name="regulationstatus",
            ),
            nullable=False,
        ),
        sa.Column("regulation_basis", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("NEW", "ACTIVE", "STALE", "REJECTED", name="opportunitystatus"),
            nullable=False,
        ),
        sa.Column("analysis_run_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("source_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parser_name", sa.String(), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "HTML_SELECTOR",
                "JSON_FIELD",
                "API_RESPONSE",
                "MANUAL",
                "FIXTURE",
                "DERIVED",
                name="extractionmethod",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("model_provider", sa.String(), nullable=True),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("ai_run_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ai_run_id"],
            ["ai_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_opportunity_product_id"), "opportunity", ["product_id"], unique=False)
    op.create_table(
        "product_variant",
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("market_id", sa.UUID(), nullable=False),
        sa.Column("title_raw", sa.Text(), nullable=False),
        sa.Column("title_language", sa.String(length=8), nullable=False),
        sa.Column("brand_raw", sa.String(length=255), nullable=True),
        sa.Column(
            "identifier_type",
            sa.Enum(
                "JAN",
                "EAN",
                "UPC",
                "GTIN",
                "ISBN",
                "MPN",
                "MODEL_NUMBER",
                "NONE",
                name="identifiertype",
            ),
            nullable=False,
        ),
        sa.Column("identifier_value", sa.String(length=64), nullable=True),
        sa.Column("model_number", sa.String(length=128), nullable=True),
        sa.Column("dimensions_mm", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("weight_g", sa.Integer(), nullable=True),
        sa.Column("capacity", sa.String(length=64), nullable=True),
        sa.Column("material", sa.String(length=128), nullable=True),
        sa.Column("color", sa.String(length=64), nullable=True),
        sa.Column("pack_quantity", sa.Integer(), nullable=True),
        sa.Column("attributes_extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["market.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_variant_identifier_value"),
        "product_variant",
        ["identifier_value"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_variant_product_id"), "product_variant", ["product_id"], unique=False
    )
    op.create_table(
        "seller",
        sa.Column("marketplace_id", sa.UUID(), nullable=False),
        sa.Column("external_seller_id", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["marketplace_id"],
            ["marketplace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "demand_observation",
        sa.Column("product_variant_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_snapshot_id", sa.UUID(), nullable=False),
        sa.Column(
            "metric_type",
            sa.Enum(
                "SEARCH_INTEREST", "REVIEW_VELOCITY", "MANUAL_ESTIMATE", name="demandmetrictype"
            ),
            nullable=False,
        ),
        sa.Column("metric_value", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parser_name", sa.String(), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "HTML_SELECTOR",
                "JSON_FIELD",
                "API_RESPONSE",
                "MANUAL",
                "FIXTURE",
                "DERIVED",
                name="extractionmethod",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_variant_id"],
            ["product_variant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_variant_id", "metric_type", "source_snapshot_id"),
    )
    op.create_index(
        op.f("ix_demand_observation_product_variant_id"),
        "demand_observation",
        ["product_variant_id"],
        unique=False,
    )
    op.create_table(
        "entity_match",
        sa.Column("left_variant_id", sa.UUID(), nullable=False),
        sa.Column("right_variant_id", sa.UUID(), nullable=False),
        sa.Column(
            "match_type",
            sa.Enum("EXACT", "LIKELY", "POSSIBLE", "REJECTED", "UNKNOWN", name="matchtype"),
            nullable=False,
        ),
        sa.Column(
            "match_stage",
            sa.Enum(
                "IDENTIFIER",
                "ATTRIBUTES",
                "STRING",
                "FUZZY",
                "EMBEDDING",
                "VISION",
                "LLM_JUDGE",
                name="matchstage",
            ),
            nullable=False,
        ),
        sa.Column("match_confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.Column("resolved_product_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_by_human", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("source_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parser_name", sa.String(), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "HTML_SELECTOR",
                "JSON_FIELD",
                "API_RESPONSE",
                "MANUAL",
                "FIXTURE",
                "DERIVED",
                name="extractionmethod",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("model_provider", sa.String(), nullable=True),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("ai_run_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ai_run_id"],
            ["ai_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["left_variant_id"],
            ["product_variant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["right_variant_id"],
            ["product_variant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entity_match_left_variant_id"), "entity_match", ["left_variant_id"], unique=False
    )
    op.create_index(
        op.f("ix_entity_match_right_variant_id"), "entity_match", ["right_variant_id"], unique=False
    )
    op.create_table(
        "offer",
        sa.Column("product_variant_id", sa.UUID(), nullable=False),
        sa.Column("marketplace_id", sa.UUID(), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=True),
        sa.Column("listing_url", sa.Text(), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "INACTIVE", "UNKNOWN", name="offerstatus"), nullable=False
        ),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["marketplace_id"],
            ["marketplace.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_variant_id"],
            ["product_variant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("marketplace_id", "listing_url"),
    )
    op.create_index(
        op.f("ix_offer_product_variant_id"), "offer", ["product_variant_id"], unique=False
    )
    op.create_table(
        "review_observation",
        sa.Column("product_variant_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("average_rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parser_name", sa.String(), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "HTML_SELECTOR",
                "JSON_FIELD",
                "API_RESPONSE",
                "MANUAL",
                "FIXTURE",
                "DERIVED",
                name="extractionmethod",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_variant_id"],
            ["product_variant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_variant_id", "source_snapshot_id"),
    )
    op.create_index(
        op.f("ix_review_observation_product_variant_id"),
        "review_observation",
        ["product_variant_id"],
        unique=False,
    )
    op.create_table(
        "user_decision",
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("user_email", sa.String(length=255), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("BUY_TEST", "WATCH", "REJECT", "ARCHIVE", name="decisiontype"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_decision_opportunity_id"), "user_decision", ["opportunity_id"], unique=False
    )
    op.create_table(
        "inventory_observation",
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("in_stock", sa.Boolean(), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parser_name", sa.String(), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "HTML_SELECTOR",
                "JSON_FIELD",
                "API_RESPONSE",
                "MANUAL",
                "FIXTURE",
                "DERIVED",
                name="extractionmethod",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("offer_id", "source_snapshot_id"),
    )
    op.create_index(
        op.f("ix_inventory_observation_offer_id"),
        "inventory_observation",
        ["offer_id"],
        unique=False,
    )
    op.create_table(
        "price_observation",
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("price_amount", sa.Integer(), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parser_name", sa.String(), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "HTML_SELECTOR",
                "JSON_FIELD",
                "API_RESPONSE",
                "MANUAL",
                "FIXTURE",
                "DERIVED",
                name="extractionmethod",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("offer_id", "source_snapshot_id"),
    )
    op.create_index(
        op.f("ix_price_observation_offer_id"), "price_observation", ["offer_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_observation_offer_id"), table_name="price_observation")
    op.drop_table("price_observation")
    op.drop_index(op.f("ix_inventory_observation_offer_id"), table_name="inventory_observation")
    op.drop_table("inventory_observation")
    op.drop_index(op.f("ix_user_decision_opportunity_id"), table_name="user_decision")
    op.drop_table("user_decision")
    op.drop_index(op.f("ix_review_observation_product_variant_id"), table_name="review_observation")
    op.drop_table("review_observation")
    op.drop_index(op.f("ix_offer_product_variant_id"), table_name="offer")
    op.drop_table("offer")
    op.drop_index(op.f("ix_entity_match_right_variant_id"), table_name="entity_match")
    op.drop_index(op.f("ix_entity_match_left_variant_id"), table_name="entity_match")
    op.drop_table("entity_match")
    op.drop_index(op.f("ix_demand_observation_product_variant_id"), table_name="demand_observation")
    op.drop_table("demand_observation")
    op.drop_table("seller")
    op.drop_index(op.f("ix_product_variant_product_id"), table_name="product_variant")
    op.drop_index(op.f("ix_product_variant_identifier_value"), table_name="product_variant")
    op.drop_table("product_variant")
    op.drop_index(op.f("ix_opportunity_product_id"), table_name="opportunity")
    op.drop_table("opportunity")
    op.drop_index(op.f("ix_insight_product_id"), table_name="insight")
    op.drop_table("insight")
    op.drop_table("source_snapshot")
    op.drop_table("product")
    op.drop_table("marketplace")
    op.drop_index(op.f("ix_event_entity_id"), table_name="event")
    op.drop_table("event")
    op.drop_table("ai_run")
    op.drop_table("watchlist_item")
    op.drop_table("source")
    op.drop_table("raw_object")
    op.drop_table("market")
    op.drop_index(op.f("ix_manufacturer_name_normalized"), table_name="manufacturer")
    op.drop_table("manufacturer")
    op.drop_index(op.f("ix_brand_name_normalized"), table_name="brand")
    op.drop_table("brand")
    op.drop_table("analysis_run")
    # ### end Alembic commands ###
    # Autogenerate does not emit DROP TYPE for native Postgres enums used by
    # dropped columns/tables above, leaving orphaned types that break a
    # subsequent upgrade (CREATE TYPE ... already exists). Drop them
    # explicitly so downgrade -> upgrade is round-trip safe.
    for enum_name in (
        "airunpurpose",
        "airunstatus",
        "analysisrunstatus",
        "analysisruntype",
        "decisiontype",
        "demandmetrictype",
        "evententitytype",
        "eventtype",
        "extractionmethod",
        "identifiertype",
        "marketplacetype",
        "matchstage",
        "matchtype",
        "offerstatus",
        "opportunitystatus",
        "opportunitytype",
        "productstatus",
        "regulationstatus",
        "reliabilitylevel",
        "snapshotstatus",
        "sourcetype",
        "trusttier",
        "watchlistentitytype",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    op.execute("DROP EXTENSION IF EXISTS vector")
